language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "zeroturnaround"
    token:
      secure: "dFNgwt3sxnNxGwV4A/TIGB/RnUxaGj6fghwZH6hhj2t74+Tt5AC59XSpXN+CcPJ1YBZzsWdjTI5Q1rMkZn5cNQ5LTto8uYRLbZNlJlEn1A/kAqPnInNu+TBziIW9ykoDvm8pS6t2itSlRDl7Udbf4Vx1bzi8ycZRtDEuzWkuV4M="
jdk:
  - oraclejdk8
script:
  - git fetch --unshallow
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
